### ISSUE TITLE
Not the AKS test

### ISSUE THREAD

**Issue by danaj** [sibu-github/aks_primality_test#1]
As currently written, this is not the AKS test.

See:  https://www.cse.iitk.ac.in/users/manindra/algebra/primality_v6.pdf

This implements the introductory Lemma 2.1, which was known before 1700 and is exponential time.  It is, in fact, significantly less efficient than naive trial division.

Unfortunately the popular Numberphile video did not make this clear, and this mistake has been propagated to sites such as [RosettaCode](http://rosettacode.org/wiki/AKS_test_for_primes).

_As an aside, not an issue, even the significantly improved AKS algorithm from Bernstein et al. is much slower in practice than APR-CL and ECPP.  These are both primality proof methods, not probabilistic.  Of course Miller-Rabin and BPSW are vastly faster than any of the general form proof methods._

**Comment by sibu-github** [comment]
Ok, I was misled by the Numberphile video as well. Thanks for the correct info and the source. I will try to implement the actual algorithm.

**Comment by sibu-github** [comment]
AKS Algorithm corrected.
